import os
from typing import Callable
from typing import Optional

from classes.PostBridge import PostBridge
from classes.PostBridge import PostBridgeClientError
from config import get_post_bridge_config
from status import info
from status import question
from status import success
from status import warning


def resolve_social_account_ids(
    client: PostBridge,
    configured_account_ids: list[int],
    platforms: list[str],
    interactive: bool,
    prompt_fn: Optional[Callable[[str], str]] = None,
) -> list[int]:
    """
    Resolve the social account IDs to use for a cross-post.

    Args:
        client (PostBridge): Post Bridge client instance.
        configured_account_ids (list[int]): Preconfigured account IDs.
        platforms (list[str]): Target platforms in config order.
        interactive (bool): Whether prompting is allowed.
        prompt_fn (Callable | None): Optional prompt function override for tests.

    Returns:
        account_ids (list[int]): Resolved target account IDs.
    """
    if configured_account_ids:
        return configured_account_ids

    if prompt_fn is None:
        prompt_fn = question

    accounts = client.list_social_accounts(platforms=platforms)
    accounts_by_platform = {}
    for account in accounts:
        platform = account.get("platform")
        accounts_by_platform.setdefault(platform, []).append(account)

    resolved_account_ids = []

    for platform in platforms:
        platform_accounts = accounts_by_platform.get(platform, [])

        if len(platform_accounts) == 0:
            warning(f"No connected Post Bridge accounts found for {platform}.")
            continue

        if len(platform_accounts) == 1:
            selected_account = platform_accounts[0]
            info(
                f"Using Post Bridge account for {platform}: "
                f"@{selected_account.get('username', '?')}"
            )
            resolved_account_ids.append(selected_account["id"])
            continue

        if not interactive:
            warning(
                f"Multiple Post Bridge accounts found for {platform}. "
                "Configure account_ids in config.json or run interactively."
            )
            return []

        info(f"Multiple Post Bridge accounts found for {platform}:")
        for index, account in enumerate(platform_accounts, start=1):
            info(
                f" {index}. @{account.get('username', '?')} "
                f"(ID: {account['id']})",
                False,
            )

        while True:
            choice = prompt_fn(
                f"Select the {platform} account to use (1-{len(platform_accounts)}): "
            ).strip()
            try:
                selected_index = int(choice) - 1
            except ValueError:
                warning("Invalid selection. Please enter a number.")
                continue

            if 0 <= selected_index < len(platform_accounts):
                selected_account = platform_accounts[selected_index]
                resolved_account_ids.append(selected_account["id"])
                break

            warning("Invalid selection. Please try again.")

    if resolved_account_ids:
        info(
            "Tip: Add these Post Bridge account IDs to config.json to skip prompts:"
        )
        info(f' "account_ids": {resolved_account_ids}', False)

    return resolved_account_ids


def build_platform_configurations(title: str) -> dict:
    """
    Build platform-specific post overrides for Post Bridge.

    Args:
        title (str): Video title generated by YouTube flow.

    Returns:
        platform_configurations (dict): Platform override payload.
    """
    cleaned_title = title.strip()
    if not cleaned_title:
        return {}

    return {
        "tiktok": {
            "title": cleaned_title,
        }
    }


def maybe_crosspost_youtube_short(
    video_path: str,
    title: str,
    interactive: bool,
    prompt_fn: Optional[Callable[[str], str]] = None,
) -> Optional[bool]:
    """
    Cross-post a successfully uploaded YouTube Short via Post Bridge.

    Args:
        video_path (str): Path to generated video file.
        title (str): Generated YouTube title.
        interactive (bool): Whether prompting is allowed.
        prompt_fn (Callable | None): Optional prompt function override for tests.

    Returns:
        result (bool | None): True when posted, False when attempted and failed,
            None when skipped.
    """
    config = get_post_bridge_config()

    if not config["enabled"]:
        return None

    if not config["api_key"]:
        warning(
            "Post Bridge is enabled but no API key is configured. "
            "Set post_bridge.api_key or POST_BRIDGE_API_KEY."
        )
        return None

    if not os.path.exists(video_path):
        warning(f"Cannot cross-post because the video file was not found: {video_path}")
        return False

    platforms = config["platforms"]
    configured_account_ids = config["account_ids"]
    if not platforms and not configured_account_ids:
        warning("Post Bridge is enabled but no supported platforms are configured.")
        return None

    if prompt_fn is None:
        prompt_fn = question

    if interactive:
        should_crosspost = config["auto_crosspost"]
        if not should_crosspost:
            platform_label = ", ".join(platforms) if platforms else "configured Post Bridge accounts"
            response = prompt_fn(
                f"Cross-post this video to {platform_label} via Post Bridge? (Yes/No): "
            ).strip().lower()
            should_crosspost = response in {"y", "yes"}
    else:
        if not config["auto_crosspost"]:
            info(
                "Post Bridge is enabled, but auto_crosspost is disabled. "
                "Skipping cross-post in cron mode."
            )
            return None
        should_crosspost = True

    if not should_crosspost:
        return None

    post_caption = title.strip()
    if not post_caption:
        post_caption = os.path.splitext(os.path.basename(video_path))[0]

    client = PostBridge(config["api_key"])

    try:
        account_ids = resolve_social_account_ids(
            client=client,
            configured_account_ids=configured_account_ids,
            platforms=platforms,
            interactive=interactive,
            prompt_fn=prompt_fn,
        )
        if not account_ids:
            warning("No Post Bridge accounts were resolved. Skipping cross-post.")
            return None

        media_id = client.upload_media(video_path)
        result = client.create_post(
            caption=post_caption,
            social_account_ids=account_ids,
            media_ids=[media_id],
            platform_configurations=build_platform_configurations(title),
        )

        success(f"Cross-posted via Post Bridge (post ID: {result.get('id', 'unknown')}).")
        for warning_message in result.get("warnings", []):
            warning(f"Post Bridge warning: {warning_message}")
        return True
    except PostBridgeClientError as exc:
        warning(f"Post Bridge cross-post failed: {exc}")
        return False
